USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS IN ZOMATO_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPENT = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPEND = TRUE;

-- Database + medallion schemas
CREATE DATABASE IF NOT EXISTS ZOMATO;
CREATE SCHEMA IF NOT EXISTS ZOMATO.BRONZE;
CREATE SCHEMA IF NOT EXISTS ZOMATO.RAW;
CREATE SCHEMA IF NOT EXISTS ZOMATO.STAGING;
CREATE SCHEMA IF NOT EXISTS ZOMATO.SNAPSHOTS
CREATE SCHEMA IF NOT EXISTS ZOMATO.STORAGE_AWS_IAM_USER_ARN

-- A role dbt/Airflow will use
CREATE ROLE IF NOT EXISTS IN DBT_ROLE;
GRANT USAGE ON WAREHOUSE ZOMATO_WH TO ROLE DBT_ROLE;
GRANT OPERATE ON WAREHOUSE ZOMATO_WH TO ROLE DBT_ROLE;
GRANT ALL ON DATABASE ZOMATO TO ROLE DBT_ROLE;
GRANT ALL ON ALL SCHEMAS IN DATABASE ZOMATO TO ROLE DBT_ROLE;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE ZOMATO TO DBT_ROLE;
GRANT ALL ON FUTURE TABLES IN DATABASE TO ZOMATO TO ROLE DBT_ROLE;
GRANT ALL ON FUTURE TABLES IN DATABASE ZOMATO TO ROLE DBT_ROLE;
GRANT ALL ON FUTURE VIEWS IN DATABASE ZOMATO TO ROLE DBT_ROLE;